default: &default
  adapter: postgresql
  encoding: utf8
  host: localhost
  port: 5432
  username: postgres
  password: admin
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: mydb

test:
  <<: *default
  database: mydb

production:
  <<: *default
  database: mydb
